### ISSUE TITLE
i18n/L10n

### ISSUE THREAD

**Issue by leonardcj** [sugarlabs/Make-Them-Fall#1]
Please add internationalization so we can add to Pootle

**Comment by leonardcj** [comment]
ping

**Comment by iamutkarshtiwari** [comment]
@leonardcj Hi! I forgot how to add internalization to the activities :/ Could you please guide me?

**Comment by leonardcj** [comment]
http://www.flossmanuals.net/make-your-own-sugar-activities/going-international-with-pootle/

**Comment by iamutkarshtiwari** [comment]
At the time of writing this activity, I didn't know much about internationlization so most of the text in it are in the Image format, but I'll make sure all strings go through gettext.

**Comment by iamutkarshtiwari** [comment]
@leonardcj Pootle added 👍 Unfortunately there were only two words which could be translated, rest all are in form of textual images :/

**Comment by iamutkarshtiwari** [comment]
@leo
